pipeline {
    agent { label 'Back-agent' }
    tools {
        maven 'maven'
        jdk 'jdk21'
    }
    environment {
        JAVA_HOME = '/usr/lib/jvm/openjdk-21'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/amiraz014/Sirius-ing2-hopital.git'
            }
        }
        stage('Install') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Build') {
            steps {
                sh 'pwd && mvn package'
            }
        }
        stage('Deploy to Prod') {
            steps {
                sh 'echo m6 | sudo -S systemctl restart runBack.service'
            }
        }
       stage('Deploy to Server') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'ssh-credentials-id', passwordVariable: 'PASSWORD', usernameVariable: 'USER')]) {
                        sh '''
                        sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USER@172.31.253.227 "$COMMAND_TO_RUN"
                        '''
                    }
        }
    }
    }
    }
}