pipeline {
    agent any
    environment{
        REOMTE_URL = "https://github.com/amiraz014/Sirius-ing2-hopital.git"

    }

    stages{
        stage('clone'){
            steps {
            git branch: "main", url:"${env.REOMTE_URL}"
            }
        }
        stage('install'){
            steps{
                sh '''
                        cd Ing2-proto/proto-front
                        rm -rf node_modules package-lock.json
                        npm cache clean --force
                        npm cache verify
                        npm install --no-optional
                        npm install rollup --save-dev
                        node --version
                        npm --version
                '''
            }
        }
        stage('build'){
            steps{
                sh '''
                        npm run build
                '''
            }
        }
        stage ('deploy'){
            steps {
                sh '''

                '''
            }
        }
    }
}