pipeline {
    agent none
    environment {
        REPO_URL = "https://github.com/amiraz014/Sirius-ing2-hopital.git"
        REMOTE_USER = "eco"
    }
    stages {
        stage('Cloning the repository') {
            agent {
                docker {
                     image 'ecotracer/front-agent'
                    args '--user root --entrypoint=""'
                }
            }
            steps {
                git branch: "main", url: "${env.REPO_URL}"
            }
        }

        stage("Build") {
            agent {
                docker {
                    image 'ecotracer/front-agent'
                    args '--user root'
                }
            }
            steps {
                script {
                    sh '''
                        ls -la
                        rm -rf node_modules package-lock.json
                        npm cache clean --force
                        npm install --no-optional
                        npm install rollup --save-dev
                        node --version
                        npm --version
                        npm run build
                        ls -la
                    '''
                }
            }
        }
    }
}