pipeline {
  agent {label 'dev-back'}

  environment{
    REOMTE_URL = "https://github.com/amiraz014/Sirius-ing2-hopital.git"
     JAVA_HOME='/usr/lib/jvm/java-21-openjdk-amd64'
'

  }
  stages {
    stage('clone'){
      steps {
        git branch: "main", url:"${env.REOMTE_URL}"
      }
    }
    stage('install'){
      steps {
        sh '''
             cd Ing2-proto/proto-back
             mvn install
             mvn --version

        '''
      }
    }
    stage ('build') {
      steps {
        sh '''
            mvn clean package
        '''
      }
    }
    stage ('deploy') {
      steps {
        sh '''
          cd /home/devback/workspace/dev-back/Ing2-proto/proto-back/
          mvn springboot:run
         '''
      }
    }

  }
}